version: '3.8'

services:
  nginx:
    build: infra/nginx
    ports:
      - "3000:3000"
    depends_on:
      - app
  app:
    build: ./
    ports:
      - "3001:3001"
      - "8000:8000"
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mafia-ai
      POSTGRES_USER: mafiadev
      POSTGRES_PASSWORD: mafia123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  searxng:
    image: searxng/searxng
    restart: always
    environment:
      BASE_URL: http://0.0.0.0:8080/
      INSTANCE_NAME: searxng
    ports:
      - "8001:8080"
    volumes:
      - ./infra/searxng:/etc/searxng:rw

volumes:
  postgres_data:
