models:
  - name: "gpt-3.5-turbo"
    type: "openai"
    base_url: "https://oneapi.xty.app/v1/"
    api_key: ""
  - name: "gpt-4o-mini"
    type: "openai"
    base_url: "https://oneapi.xty.app/v1/"
    api_key: ""
  - name: "qwen2.5:7b"
    type: "ollama"
    base_url: ""
    api_key: ""
  - name: "deepseek-chat"
    type: "deepseek"
    base_url: "https://api.deepseek.com"
    api_key: ""
tool_model: "gpt-3.5-turbo"
chat_model: "gpt-3.5-turbo"
embedding:
  meta: "gpt-3.5-turbo"
  model: "text-embedding-ada-002"
  persist_dir: "data/embd"
file_dir: "data/files"
max_tokens: 2000
max_histories: 20
crawler:
  interval: 60
admin_pwd: "123456"
tavily:
  enabled: true
  key: ""
database:
  host: "database"
  port: "5432"
  username: "mafiadev"
  password: "mafia123"
  schema: "mafia-ai"
smtp:
  email: ""
  password: ""
searx:
  host: "searxng"
  port: "8080"
  limit: 10
  engines:
    - "baidu"
    - "360search"
    - "sogou"
#    - "google"
#    - "bing"
#    - "yahoo"
api:
  port: 8000
  key: "mafia123"
