models:
  - name: "gpt-3.5-turbo"
    type: "openai"
    base_url: "https://oneapi.xty.app/v1/"
    api_key: ""
  - name: "gpt-4o-mini"
    type: "openai"
    base_url: "https://oneapi.xty.app/v1/"
    api_key: ""
  - name: "qwen2.5:7b"
    type: "ollama"
    base_url: ""
    api_key: ""
tool_model: "gpt-3.5-turbo"
chat_model: "gpt-3.5-turbo"
embedding_model: "gpt-3.5-turbo"
admin_pwd: "123456"
tavily:
  enabled: true
  key: ""
database:
  host: "localhost"
  port: "5432"
  username: "mafiadev"
  password: "mafia123"
  schema: "mafia-ai"
api:
  port: 8000
  key: "mafia123"
ip_pool:
  enabled: false
  urls:
    - https://www.proxy-list.download/api/v2/get?l=en&t=http
    - http://api.89ip.cn/tqdl.html?api=1&num=200&port=&address=&isp=
    - https://openproxy.space/list/http
    - http://www.ip3366.net/free/